version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ''
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  redis:
    image: 'redis:latest'

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
    - '3050:80'
    depends_on:
      - api
      - client

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
    - /app/node_module
    - ./api:/app
    stdin_open: true
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_module
      - ./client:/app
    stdin_open: true

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_module
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379